### ISSUE TITLE
Region GPU Plugin Does Not Turn On

### ISSUE THREAD

**Issue by rxdps93** [slaytostay/region-locker#38]
As the title implies when I toggle on the Region GPU plugin it immediately turns off. Default GPU plugin and 117HD plugins both work without issue.

This is happening on a Macbook Pro Mid 2014 Retina, with the dedicated GPU: Nvidia GeForce GE 750M, running MacOS Catalina 10.15.7.

Here is the relevant section from client.log:
```
2023-08-03 21:39:29 EDT [Client] INFO  com.gpu.RegionLockerGpuPlugin - Using device: NVIDIA GeForce GT 750M OpenGL Engine
2023-08-03 21:39:29 EDT [Client] INFO  com.gpu.RegionLockerGpuPlugin - Using driver: 4.1 NVIDIA-14.0.32 355.11.11.10.10.143
2023-08-03 21:39:29 EDT [Client] INFO  com.gpu.RegionLockerGpuPlugin - unsupported swap interval -1, got 0
2023-08-03 21:39:29 EDT [Client] ERROR com.gpu.OpenCLManager - [LWJGL] cl_context_callback: [CL_INVALID_DEVICE] : OpenCL Error : clCreateCommandQueue failed: Unable to locate device 0x1024500 in context 0x600000ff06e0.
2023-08-03 21:39:29 EDT [Client] ERROR com.gpu.OpenCLManager - [LWJGL] cl_context_callback: [CL_INVALID_DEVICE] : OpenCL Error : clGetProgramBuildInfo failed: Device 0x1024500 not in context 0x600000ff06e0
2023-08-03 21:39:29 EDT [Client] ERROR com.gpu.RegionLockerGpuPlugin - Error starting GPU plugin
java.lang.RuntimeException: OpenCL error [-33]
	at com.gpu.OpenCLManager.checkCLError(OpenCLManager.java:571)
	at com.gpu.OpenCLManager.getProgramBuildInfoInt(OpenCLManager.java:542)
	at com.gpu.OpenCLManager.compileProgram(OpenCLManager.java:335)
	at com.gpu.OpenCLManager.compilePrograms(OpenCLManager.java:366)
	at com.gpu.OpenCLManager.init(OpenCLManager.java:133)
	at com.gpu.RegionLockerGpuPlugin.initProgram(RegionLockerGpuPlugin.java:582)
	at com.gpu.RegionLockerGpuPlugin.lambda$startUp$1(RegionLockerGpuPlugin.java:378)
	at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:217)
	at client.ce(client.java:56174)
	at client.bw(client.java)
	at bq.bd(bq.java:363)
	at bq.run(bq.java:342)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-08-03 21:39:29 EDT [Client] ERROR n.r.client.callback.ClientThread - Exception in invoke
java.lang.NullPointerException: null
	at org.lwjgl.system.Checks.check(Checks.java:188)
	at org.lwjgl.opencl.CL10.clReleaseKernel(CL10.java:5760)
	at com.gpu.OpenCLManager.cleanup(OpenCLManager.java:146)
	at com.gpu.RegionLockerGpuPlugin.lambda$shutDown$2(RegionLockerGpuPlugin.java:462)
	at net.runelite.client.callback.ClientThread.lambda$invoke$0(ClientThread.java:49)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:62)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:47)
	at com.gpu.RegionLockerGpuPlugin.shutDown(RegionLockerGpuPlugin.java:436)
	at com.gpu.RegionLockerGpuPlugin.lambda$startUp$1(RegionLockerGpuPlugin.java:427)
	at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:217)
	at client.ce(client.java:56174)
	at client.bw(client.java)
	at bq.bd(bq.java:363)
	at bq.run(bq.java:342)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by aHooder** [comment]
This will be fixed once this pull request passes review by the RuneLite team: https://github.com/runelite/plugin-hub/pull/4720
